language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:headless || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - REPO_NAME=d2l-content-store
  - OWNER_NAME=Brightspace
  # GITHUB_RELEASE_TOKEN (ae7d......bd1e)
  - secure: mKn7U51dGx9k3seYHtcmS8vQv9aNCEnFS33Z4k0MjD3ebJGBQz5IIff9jzjh6xUjZFRjADDWnLwuuVidXvagTuxkukOmKQ8h7JpnwzW58qj8boYfKCL9y7CS99HaMo6m5yLVYEGZnvELOTx1MO13cS2DYk0M4LZOXzmOZY5AOo0MtiqPIEMq3PpXNu1JAx7gC9OttWUjK+/ieertT9UVd62/TpwJkJFtvfLNLpyLe6VNCdMVyH1i5BSMeIz3q0wSfd0sk/QSddPBzCK50mJsKO/LPM7yfwmGs/cDc8TIqxTXhj/zeLUu43khromkNNMXgCflMfXTIKX7R2bALvqLQYKCtvaH9cHkEcXBWPr1+5tT8AgnfNEqkZJ5+osA1POQ4C/6ZWPcm9EYmiZXm5e4gH0t6Gw6JrSpEG1pAvqOHaRsFXOiRVZlpt8W2KHgoZKXsz2SQ9Z6OH6w8RP3H1gBmS/pKfI9Rr9aPMlcolmpr/ogfWzx0g4ZARXp/Cr0/8mTYEJ+Lt00CtH5u36PcSsIiL6gOxyjDA56c4Z6IwlHdxwIj/2dbc7CGwfi31faaRj0r4N1gWFtedZQBU7DHa/Ri8eNH9E04rlIV2HTW+KPjkcIW4HklV7NJxmndASw8mu88vaXGuk3kwcCJFAbrkpXvbvbU/Ka8IOWTjaL3AE2gh4=
